# A preset favoring shades of green and bluish green,
# with refreshing bright white input.

source "$yazpt_default_preset_file"

YAZPT_LAYOUT=$'\n<cwd><? ><result><? ><git>\n%# '

YAZPT_CWD_COLOR=23
YAZPT_GIT_WRAPPER_CHARS="()"
YAZPT_GIT_BRANCH_COLOR=34

YAZPT_GIT_STATUS_CLEAN_CHAR=""
YAZPT_GIT_STATUS_DIRTY_CHAR_COLOR=229
YAZPT_GIT_STATUS_DIVERGED_CHAR_COLOR=230
YAZPT_GIT_STATUS_NO_UPSTREAM_CHAR_COLOR=240

YAZPT_RESULT_ERROR_CHAR=""
YAZPT_RESULT_ERROR_CODE_COLOR=36
YAZPT_RESULT_OK_CODE_COLOR=36
YAZPT_RESULT_OK_CODE_VISIBLE=true

zle_highlight=(default:fg=254 suffix:fg=243)
